In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5])
b = np.array([[1,2,3],
             [4,5,6]])
c = np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
              [['J','K','L'],['M','N','O'],['P','Q','R']],
              [['S','T','U'],['V','W','X'],['Y','Z','_']]]
              )
print(c.shape)
#(3, 3, 3)
#depth, no. of rows, no. of columns

(3, 3, 3)


In [5]:
#multi dimensional indexing
print(c[1,1,1])
word = c[2,0,1]+c[2,0,2]+c[0,2,0]
print(word)

N
TUG


In [6]:
#slicing
array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])
#array[start:end:step]

#row selection
print(array[0:4:2])
#column selection
#array[row,column]
print(array[:,1])
print(array[:,0:3])
#both row and column selection
print(array[0:2,0:2])

[[ 1  2  3  4]
 [ 9 10 11 12]]
[ 2  6 10 14]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
[[1 2]
 [5 6]]


In [7]:
# scalar arithmetic
arr = np.array([1.01,2.5,3.99])
print(arr+1)
print(arr-2)
print(arr*3)
print(arr/4)
print(arr**5)

[2.01 3.5  4.99]
[-0.99  0.5   1.99]
[ 3.03  7.5  11.97]
[0.2525 0.625  0.9975]
[   1.05101005   97.65625    1011.2638402 ]


In [8]:
#vectorized math funcs
#print(np.sqrt(arr))
print(np.ceil(arr))

[2. 3. 4.]


In [12]:
array1 = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12],
                   [13,14,15,1]])
array2 = np.array([[1],[2],[3],[4]])

print(array1.shape)
print(array2.shape)

print(array1*array2)

(4, 4)
(4, 1)
[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]
 [52 56 60  4]]


In [21]:
#aggregate functions = summarize data and typically
#                      return a single value
array3 = np.array([[1,2,3,4,5],
                   [6,7,8,9,10]])
# print(np.sum(array3))
# print(np.mean(array3))
# print(np.std(array3))
# print(np.var(array))
# print(np.max(array3))
# print(np.argmin(array))


0


In [31]:
#Filtering - refers to the process of selecting elements
#            from an array that match a given condition

ages = np.array([[21,17,19,20,16,30,18,65],
                 [39,22,15,99,18,19,20,21]])

# teenagers = ages[ages<18]
# adults = ages[(ages >=18) & (ages<65)]
# seniors = ages[ages >= 65]
# evens = ages[ages%2 == 0]
# odds = ages[ages%2 != 0]

# preserving shape of 2D array - where
adults = np.where(ages>=18, ages, 0)
print(adults)

[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]


In [39]:
rng = np.random.default_rng()

print(rng.integers(low=1,high=7, size=(3,2)))

[6 2 4]
